"""empty message

Revision ID: a619377288c1
Revises: 3d13db8c3e1d
Create Date: 2023-01-11 23:48:38.238562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a619377288c1'
down_revision = '3d13db8c3e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('account', sa.Column('item', sa.String(length=100), nullable=False))
    op.add_column('account', sa.Column('spend', sa.Integer(), nullable=False))
    op.drop_column('account', 'title')
    op.drop_column('account', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('content', mysql.TEXT(), nullable=False))
    op.add_column('account', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('account', 'spend')
    op.drop_column('account', 'item')
    op.drop_column('account', 'date')
    # ### end Alembic commands ###
